#!/bin/bash -x

sleep 2

unset x y w h
eval $(xwininfo -id $(xdotool getactivewindow) |
sed -n -e "s/^ \+Absolute upper-left X: \+\([0-9]\+\).*/x=\1/p" \
    -e "s/^ \+Absolute upper-left Y: \+\([0-9]\+\).*/y=\1/p" \
    -e "s/^ \+Width: \+\([0-9]\+\).*/w=\1/p" \
    -e "s/^ \+Height: \+\([0-9]\+\).*/h=\1/p" )

if [ -n "$1" ]; then
    w=$(($w + 1 + 1))
    x=$(($x - 1))
    h=$(($h + 26 + 1))
    y=$(($y - 26))
fi

h=$(($h/2*2))
w=$(($w/2*2))

# echo -n "$x $y $w $h"

if [ "$1" == "c" ]; then
    ffmpeg -y -f v4l2 -framerate 15 -video_size 640x480 -i /dev/video0 -f pulse -i default -force_key_frames 00:00:00.000 out.mp4
else
    ffmpeg -y -f x11grab  -s ${w}x${h} -framerate 15 -i :0.0+${x},${y} -f pulse -i default -preset ultrafast -crf 18 -pix_fmt yuv420p out.mp4
fi







#ffmpeg -i "out.mp4" -itsoffset 0.45 -i "out.mp4" -map 0:v -map 1:a -y zzz.mp4 

